FROM golang:1.26-alpine AS builder
WORKDIR /phorcys
COPY . .
RUN ls -la
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o phorcys .
WORKDIR /fault-agent
COPY tests/integration/fault-agent .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o fault-agent .

FROM rabbitmq:4.3-management
COPY --chmod=0755 ./tests/integration/docker-entrypoint-rabbit.sh /
COPY --chmod=0755 --from=builder /phorcys/phorcys /
COPY --chmod=0755 --from=builder ./fault-agent/fault-agent /
COPY ./tests/integration/rabbitmq.conf /etc/rabbitmq/conf.d/01-rabbitmq.conf

ENTRYPOINT ["/docker-entrypoint-rabbit.sh"]
